### PR TITLE
262 show template errors

### LINKED ISSUE #214: Scheduled Report templates don't take up the width of the the available screen
## Describe the bug

image

## To Reproduce

Steps to reproduce the behaviour:

1. Open a scheduled report.

## Expected behaviour

The box should default to a wider view.

### LINKED ISSUE #262: Internal Error, Failed to add Template to Tera Context
## Describe the bug
```
2023-11-22 09:30:02.411590000 [ERROR] <scheduled::process:40>:InternalError("InternalError(\"Failed to add body template to tera instance: Error { kind: Msg(\\\"Failed to parse 'body_template'\\\"), source: Some(Error { kind: Msg(\\\" --> 6:37\\\\n  |\\\\n6 | Of the {{ num_of_stores_configured.0. num_of_stores_configured }} stores configured: </br>␊\\\\n  |                                     ^---\\\\n  |\\\\n  = expected `or`, `and`, `not`, `<=`, `>=`, `<`, `>`, `==`, `!=`, `+`, `-`, `*`, `/`, `%`, a filter, or a variable end (`}}`)\\\"), source: None }) }\")")
```

## To Reproduce

Steps to reproduce the behaviour:

## Expected behaviour

Should these internal errors create an event that the user can see in the event log?
Or errors like this should be recorded directly against the Notification Config?

## Additional context

I think this might be related to #253 ? But need to check? If so does this mean we need to do something more to fix there?

### PR DESCRIPTION
**Pull request by lache-melvin**
Closes #262 (this PR is part 2)

# 👩🏻‍💻 What does this PR do?
 

Uses the tera-web package to validate whether the templates are parse-able, and displays an error state if not. Also prevents being able to save a broken template.

Screenshot 2023-11-24 at 2 04 40 PM

Makes subject and body template fields always full width too, to prevent their width jumping around as the error shows and hides: 
i.e. this closes #214 
Screenshot 2023-11-24 at 2 06 49 PM

# 🧪 How has/should this change been tested?

### CODE REVIEW

File: frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx [hunk 1]
```diff
@@ -55,9 +56,19 @@ export const ScheduledNotificationEditPage = () => {
...
+    } catch (e) {
+      return false;
+    }
+  };
+
   const isInvalid =
     !draft.title ||
-    // nothing selected
+    !isValidTemplate(draft.subjectTemplate) ||
+    !isValidTemplate(draft.bodyTemplate) ||
```
Comment (lache-melvin) [inline frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx:71]: Is it a valid notification with a subject but no body? Or the body/message is required also?

Comment (jmbrunskill) [reply frontend/packages/system/src/Notifications/Pages/Scheduled/ScheduledNotificationEditPage.tsx:71]: I think we should always have a body.
Telegram only renders the body, subject is just for email in current design.

**Review by jmbrunskill — APPROVED** [review]
Awesome! Love it.
