### PR TITLE
266 - Fixup tool tip errors

### LINKED ISSUE #266: React forward ref errors with Tooltip
## Describe the bug

I'm getting React warnings on both the events list and event details pages, about an issue with the forward refs for some `Tooltip`s...

Event list: 
Screenshot 2023-11-23 at 9 09 32 AM

Event details:
Screenshot 2023-11-23 at 9 09 44 AM

## To Reproduce

Steps to reproduce the behaviour:

## Expected behaviour

No errors

### PR DESCRIPTION
**Pull request by EthanMcQ-TMF**
Closes #266

# 👩🏻‍💻 What does this PR do?
 
Fix console errors that occur when displaying certain tooltips.

# 🧪 How has/should this change been tested?

Loading up the events view and checking the console, you should no longer see tooltip errors.

These errors were also causing the tooltips to fail to display, so you should now be able to hover over date entries and actually see the tooltip

Screenshot 2024-03-01 at 16 41 43

Screenshot 2024-03-01 at 16 45 44

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: frontend/packages/system/src/NotificationEvents/DetailView/DetailView.tsx [hunk 1]
```diff
@@ -53,20 +53,22 @@ export const DetailView = () => {
...
-                  )
-                );
-              }}
-              variant="outlined"
-              endIcon={<EditIcon />}
-            >
-              {t('button.edit-notification-config')}
-            </BaseButton>
+            <div>
+              <BaseButton
```
Comment (EthanMcQ-TMF) [inline frontend/packages/system/src/NotificationEvents/DetailView/DetailView.tsx:57]: Mui tooltip expects it's child to accept `ref` which react function components do not. A simple fix is to just... wrap it in a non-function component

**Review by jmbrunskill — APPROVED** [review]
Thanks! I didn't realise the reason but fixed something similar recently.
Wrapping in a non-functional component seems to be a good quick fix.
